# Generated by Django 5.0.7 on 2024-07-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_of_machine', models.CharField(max_length=255)),
                ('serial_number_of_engine', models.CharField(max_length=255)),
                ('serial_number_of_transmission', models.CharField(max_length=255)),
                ('serial_number_of_drive_axle', models.CharField(max_length=255)),
                ('serial_number_of_steering_axle', models.CharField(max_length=255)),
                ('supply_contract_number_and_date', models.CharField(max_length=255)),
                ('date_shipped_from_factory', models.DateField(null=True)),
                ('recipient', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('equipment', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driveaxlemodel')),
                ('model_of_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enginemodel')),
                ('model_of_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipmentmodel')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecompany')),
                ('steering_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.steeringaxlemodel')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transmissionmodel')),
            ],
        ),
    ]
