# Generated by Django 5.0.7 on 2024-07-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(null=True)),
                ('operating_time', models.IntegerField()),
                ('work_order_number', models.CharField(max_length=255)),
                ('work_order_date', models.DateField(null=True)),
                ('the_organization_that_carried_out_the_maintenance', models.CharField(max_length=255)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecompany')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maintenancetype')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refusal', models.DateField(null=True)),
                ('operating_time', models.IntegerField()),
                ('description_of_failure', models.CharField(max_length=255)),
                ('parts_used', models.CharField(max_length=255)),
                ('recovery_date', models.DateField(null=True)),
                ('equipment_downtime', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecompany')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.failurenode')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recoverymethod')),
            ],
        ),
    ]
