from django.urls import path

from .views import (
    unauthorized_index,
    machine_list,
    machine_detail,
    MachineCreateView,
    MachineUpdateView,
    machine_delete,
    maintenance_list,
    MaintenanceCreateView,
    MaintenanceUpdateView,
    maintenance_delete,
    complaints_list,
    ComplaintCreateView,
    ComplaintUpdateView,
    complaint_delete,
    equipment_model_info,
    engine_model_info,
    transmission_model_info,
    drive_axle_model_info,
    steering_axle_model_info,
)

urlpatterns = [
    path('', unauthorized_index, name='welcome'),
    path('machines/', machine_list, name='machine_list'),
    path('machines/create/', MachineCreateView.as_view(), name='machine_create'),
    path('machines/update/<int:pk>/', MachineUpdateView.as_view(), name='machine_update'),
    path('machines/delete/<int:machine_id>/', machine_delete, name='machine_delete'),
    path('machines/<int:machine_id>/', machine_detail, name='machine_detail'),
    path('maintenances/', maintenance_list, name='maintenance_list'),
    path('maintenances/create/', MaintenanceCreateView.as_view(), name='maintenance_create'),
    path('maintenances/update/<int:pk>/', MaintenanceUpdateView.as_view(), name='maintenance_update'),
    path('maintenances/delete/<int:maintenance_id>/', maintenance_delete, name='maintenance_delete'),
    path('complaints/', complaints_list, name='complaints_list'),
    path('complaints/create/', ComplaintCreateView.as_view(), name='complaint_create'),
    path('complaints/update/<int:pk>/', ComplaintUpdateView.as_view(), name='complaint_update'),
    path('complaints/delete/<int:complaint_id>/', complaint_delete, name='complaint_delete'),
    path('machines/equipment_model_info/<int:equipment_model_id>/', equipment_model_info, name='equipment_model_info'),
    path('machines/engine_model_info/<int:engine_model_id>/', engine_model_info, name='engine_model_info'),
    path('machines/transmission_model_info/<int:transmission_model_id>/', transmission_model_info, name='transmission_model_info'),
    path('machines/drive_axle_model_info/<int:drive_axle_model_id>/', drive_axle_model_info, name='drive_axle_model_info'),
    path('machines/steering_axle_model_info/<int:steering_axle_model_id>/', steering_axle_model_info, name='steering_axle_model_info'),
]